name: Node
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build the bundle
      run: npm run build

    - name: Run tests
      run: npm test
